openapi: 3.0.3
info:
  title: Incident Management API
  version: 1.0.0
  description: API documentation for the Incident Management Dashboard.
paths:
  /api/auth/token/:
    post:
      operationId: auth_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/auth/token/refresh/:
    post:
      operationId: auth_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/service-requests/:
    get:
      operationId: service_requests_list
      parameters:
      - in: query
        name: assigned_to
        schema:
          type: integer
      - in: query
        name: category
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: priority
        schema:
          type: string
          enum:
          - P1
          - P2
          - P3
          - P4
        description: |-
          * `P1` - P1 - Critical
          * `P2` - P2 - High
          * `P3` - P3 - Medium
          * `P4` - P4 - Low
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: service
        schema:
          type: integer
      - in: query
        name: status
        schema:
          type: string
          enum:
          - APPROVED
          - ASSIGNED
          - CLOSED
          - DRAFT
          - FULFILLED
          - IN_PROGRESS
          - PENDING_APPROVAL
          - REJECTED
          - SUBMITTED
        description: |-
          * `DRAFT` - Draft
          * `SUBMITTED` - Submitted
          * `PENDING_APPROVAL` - Pending Approval
          * `APPROVED` - Approved
          * `REJECTED` - Rejected
          * `ASSIGNED` - Assigned
          * `IN_PROGRESS` - In Progress
          * `FULFILLED` - Fulfilled
          * `CLOSED` - Closed
      tags:
      - service-requests
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedServiceRequestList'
          description: ''
    post:
      operationId: service_requests_create
      tags:
      - service-requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceRequest'
          description: ''
  /api/service-requests/{id}/:
    get:
      operationId: service_requests_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - service-requests
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceRequest'
          description: ''
    put:
      operationId: service_requests_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - service-requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceRequest'
          description: ''
    patch:
      operationId: service_requests_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - service-requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedServiceRequestRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedServiceRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedServiceRequestRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceRequest'
          description: ''
    delete:
      operationId: service_requests_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - service-requests
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/service-requests/{id}/assign/:
    put:
      operationId: service_requests_assign_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - service-requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ServiceRequestRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceRequest'
          description: ''
    patch:
      operationId: service_requests_assign_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - service-requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedServiceRequestRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedServiceRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedServiceRequestRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceRequest'
          description: ''
components:
  schemas:
    PaginatedServiceRequestList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/ServiceRequest'
    PatchedServiceRequestRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          minLength: 1
        service:
          type: integer
          nullable: true
        category:
          type: string
          minLength: 1
          maxLength: 100
        subcategory:
          type: string
          minLength: 1
          maxLength: 100
        priority:
          $ref: '#/components/schemas/PriorityEnum'
        status:
          $ref: '#/components/schemas/StatusEnum'
        assigned_to:
          type: integer
          nullable: true
    PriorityEnum:
      enum:
      - P1
      - P2
      - P3
      - P4
      type: string
      description: |-
        * `P1` - P1 - Critical
        * `P2` - P2 - High
        * `P3` - P3 - Medium
        * `P4` - P4 - Low
    ServiceRequest:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        request_number:
          type: string
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        service:
          type: integer
          nullable: true
        category:
          type: string
          maxLength: 100
        subcategory:
          type: string
          maxLength: 100
        priority:
          $ref: '#/components/schemas/PriorityEnum'
        status:
          $ref: '#/components/schemas/StatusEnum'
        requester:
          type: integer
          readOnly: true
          nullable: true
        requester_name:
          type: string
          readOnly: true
        assigned_to:
          type: integer
          nullable: true
        assigned_to_name:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        sla_due_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        sla_status:
          type: string
          readOnly: true
        approval_status:
          type: string
          readOnly: true
      required:
      - approval_status
      - assigned_to_name
      - category
      - created_at
      - description
      - id
      - request_number
      - requester
      - requester_name
      - sla_due_at
      - sla_status
      - subcategory
      - title
      - updated_at
    ServiceRequestRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          minLength: 1
        service:
          type: integer
          nullable: true
        category:
          type: string
          minLength: 1
          maxLength: 100
        subcategory:
          type: string
          minLength: 1
          maxLength: 100
        priority:
          $ref: '#/components/schemas/PriorityEnum'
        status:
          $ref: '#/components/schemas/StatusEnum'
        assigned_to:
          type: integer
          nullable: true
      required:
      - category
      - description
      - subcategory
      - title
    StatusEnum:
      enum:
      - DRAFT
      - SUBMITTED
      - PENDING_APPROVAL
      - APPROVED
      - REJECTED
      - ASSIGNED
      - IN_PROGRESS
      - FULFILLED
      - CLOSED
      type: string
      description: |-
        * `DRAFT` - Draft
        * `SUBMITTED` - Submitted
        * `PENDING_APPROVAL` - Pending Approval
        * `APPROVED` - Approved
        * `REJECTED` - Rejected
        * `ASSIGNED` - Assigned
        * `IN_PROGRESS` - In Progress
        * `FULFILLED` - Fulfilled
        * `CLOSED` - Closed
    TokenObtainPair:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - refresh
    TokenObtainPairRequest:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - password
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
      required:
      - access
    TokenRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
